/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.faculty.qss.project.gui.userFriendlyMode.alterTable;

/**
 *
 * @author echilaboc
 */
public class AlterTablePanel extends javax.swing.JPanel {

    /**
     * Creates new form AlterTablePanel
     */
    public AlterTablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAlterTable = new javax.swing.ButtonGroup();
        radioButtonChangeTableName = new javax.swing.JRadioButton();
        radioButtonDeleteColumn = new javax.swing.JRadioButton();
        radioButtonAddColumn = new javax.swing.JRadioButton();
        panelAlterTableOperation = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(469, 369));
        setSize(new java.awt.Dimension(469, 369));

        buttonGroupAlterTable.add(radioButtonChangeTableName);
        radioButtonChangeTableName.setText("Change table name");
        radioButtonChangeTableName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonChangeTableNameActionPerformed(evt);
            }
        });

        buttonGroupAlterTable.add(radioButtonDeleteColumn);
        radioButtonDeleteColumn.setText("Delete column");
        radioButtonDeleteColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonDeleteColumnActionPerformed(evt);
            }
        });

        buttonGroupAlterTable.add(radioButtonAddColumn);
        radioButtonAddColumn.setText("Add new column");
        radioButtonAddColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAddColumnActionPerformed(evt);
            }
        });

        panelAlterTableOperation.setBackground(new java.awt.Color(255, 255, 225));
        panelAlterTableOperation.setPreferredSize(new java.awt.Dimension(462, 293));
        panelAlterTableOperation.setSize(new java.awt.Dimension(462, 293));

        javax.swing.GroupLayout panelAlterTableOperationLayout = new javax.swing.GroupLayout(panelAlterTableOperation);
        panelAlterTableOperation.setLayout(panelAlterTableOperationLayout);
        panelAlterTableOperationLayout.setHorizontalGroup(
            panelAlterTableOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAlterTableOperationLayout.setVerticalGroup(
            panelAlterTableOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(radioButtonChangeTableName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(radioButtonAddColumn, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAlterTableOperation, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(radioButtonDeleteColumn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonChangeTableName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButtonAddColumn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonDeleteColumn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAlterTableOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonChangeTableNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonChangeTableNameActionPerformed
        // TODO add your handling code here:
        panelAlterTableOperation.removeAll();
        panelAlterTableOperation.revalidate();
        panelAlterTableOperation.repaint();

        ChangeTableNamePanel changeTableNamePanel = new ChangeTableNamePanel();
        panelAlterTableOperation.add(changeTableNamePanel);

        panelAlterTableOperation.setVisible(true);
    }//GEN-LAST:event_radioButtonChangeTableNameActionPerformed

    private void radioButtonDeleteColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonDeleteColumnActionPerformed
        // TODO add your handling code here:
        panelAlterTableOperation.removeAll();
        panelAlterTableOperation.revalidate();
        panelAlterTableOperation.repaint();

        DeleteColumnPanel deleteColumnPanel = new DeleteColumnPanel();
        panelAlterTableOperation.add(deleteColumnPanel);

        panelAlterTableOperation.setVisible(true);
    }//GEN-LAST:event_radioButtonDeleteColumnActionPerformed

    private void radioButtonAddColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAddColumnActionPerformed
        // TODO add your handling code here:
        panelAlterTableOperation.removeAll();
        panelAlterTableOperation.revalidate();
        panelAlterTableOperation.repaint();

        AddNewColumnPanel addNewColumnPanel = new AddNewColumnPanel();
        panelAlterTableOperation.add(addNewColumnPanel);

        panelAlterTableOperation.setVisible(true);
    }//GEN-LAST:event_radioButtonAddColumnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAlterTable;
    private javax.swing.JPanel panelAlterTableOperation;
    private javax.swing.JRadioButton radioButtonAddColumn;
    private javax.swing.JRadioButton radioButtonChangeTableName;
    private javax.swing.JRadioButton radioButtonDeleteColumn;
    // End of variables declaration//GEN-END:variables
}
