/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.faculty.qss.project.gui.userFriendlyMode.alterTable;

/**
 *
 * @author ecami
 */
public class ChangeColumnNamePanel extends javax.swing.JPanel {

    /**
     * Creates new form ChangeColumnNamePanel
     */
    public ChangeColumnNamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSelectDatabaseName = new javax.swing.JLabel();
        comboBoxDatabaseNames = new javax.swing.JComboBox<>();
        labelSelectTableName1 = new javax.swing.JLabel();
        comboBoxTableNames = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaOutput = new javax.swing.JTextArea();
        scrollPaneTypeCurrentNewColumnName = new javax.swing.JScrollPane();
        panelTypeCurrentNewColumnName = new javax.swing.JPanel();
        labelColumnType = new javax.swing.JLabel();
        labelCurrentColumnName = new javax.swing.JLabel();
        labelNewColumnName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        labelColumnDataType = new javax.swing.JLabel();
        labelCurrentColumnDataName = new javax.swing.JLabel();
        textFieldNewColumnDataName = new javax.swing.JTextField();
        labelColumnDataType1 = new javax.swing.JLabel();
        labelCurrentColumnDataName1 = new javax.swing.JLabel();
        textFieldNewColumnDataName1 = new javax.swing.JTextField();
        labelColumnDataType2 = new javax.swing.JLabel();
        labelCurrentColumnDataName2 = new javax.swing.JLabel();
        textFieldNewColumnDataName2 = new javax.swing.JTextField();

        labelSelectDatabaseName.setText("<html>Select the database</html>");

        comboBoxDatabaseNames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelSelectTableName1.setText("<html>Select the table</html>");

        comboBoxTableNames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textAreaOutput.setColumns(20);
        textAreaOutput.setRows(5);
        jScrollPane1.setViewportView(textAreaOutput);

        scrollPaneTypeCurrentNewColumnName.setHorizontalScrollBar(null);

        labelColumnType.setText("Column type");

        labelCurrentColumnName.setText("Current column name");

        labelNewColumnName.setText("New column name");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labelColumnDataType.setText("Type1");

        labelCurrentColumnDataName.setText("Column1");

        labelColumnDataType1.setText("Type1");

        labelCurrentColumnDataName1.setText("Column1");

        labelColumnDataType2.setText("Type1");

        labelCurrentColumnDataName2.setText("Column1");

        javax.swing.GroupLayout panelTypeCurrentNewColumnNameLayout = new javax.swing.GroupLayout(panelTypeCurrentNewColumnName);
        panelTypeCurrentNewColumnName.setLayout(panelTypeCurrentNewColumnNameLayout);
        panelTypeCurrentNewColumnNameLayout.setHorizontalGroup(
            panelTypeCurrentNewColumnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTypeCurrentNewColumnNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTypeCurrentNewColumnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTypeCurrentNewColumnNameLayout.createSequentialGroup()
                        .addGroup(panelTypeCurrentNewColumnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelColumnType)
                            .addComponent(labelColumnDataType)
                            .addComponent(labelColumnDataType1)
                            .addComponent(labelColumnDataType2))
                        .addGap(18, 18, 18)
                        .addGroup(panelTypeCurrentNewColumnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTypeCurrentNewColumnNameLayout.createSequentialGroup()
                                .addComponent(labelCurrentColumnName)
                                .addGap(45, 45, 45)
                                .addComponent(labelNewColumnName))
                            .addGroup(panelTypeCurrentNewColumnNameLayout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelTypeCurrentNewColumnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCurrentColumnDataName)
                                    .addComponent(labelCurrentColumnDataName1)
                                    .addComponent(labelCurrentColumnDataName2))
                                .addGap(99, 99, 99)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelTypeCurrentNewColumnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldNewColumnDataName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNewColumnDataName1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNewColumnDataName2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        panelTypeCurrentNewColumnNameLayout.setVerticalGroup(
            panelTypeCurrentNewColumnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTypeCurrentNewColumnNameLayout.createSequentialGroup()
                .addGroup(panelTypeCurrentNewColumnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelColumnType)
                    .addComponent(labelCurrentColumnName)
                    .addComponent(labelNewColumnName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTypeCurrentNewColumnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTypeCurrentNewColumnNameLayout.createSequentialGroup()
                        .addComponent(labelColumnDataType)
                        .addGap(18, 18, 18)
                        .addComponent(labelColumnDataType1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelColumnDataType2))
                    .addGroup(panelTypeCurrentNewColumnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelTypeCurrentNewColumnNameLayout.createSequentialGroup()
                            .addComponent(textFieldNewColumnDataName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldNewColumnDataName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldNewColumnDataName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelTypeCurrentNewColumnNameLayout.createSequentialGroup()
                            .addComponent(labelCurrentColumnDataName)
                            .addGap(18, 18, 18)
                            .addComponent(labelCurrentColumnDataName1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCurrentColumnDataName2))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(17, 17, 17))
        );

        scrollPaneTypeCurrentNewColumnName.setViewportView(panelTypeCurrentNewColumnName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSelectTableName1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(comboBoxTableNames, 0, 230, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSelectDatabaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxDatabaseNames, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneTypeCurrentNewColumnName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelectDatabaseName, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(comboBoxDatabaseNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelectTableName1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTableNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTypeCurrentNewColumnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxDatabaseNames;
    private javax.swing.JComboBox<String> comboBoxTableNames;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelColumnDataType;
    private javax.swing.JLabel labelColumnDataType1;
    private javax.swing.JLabel labelColumnDataType2;
    private javax.swing.JLabel labelColumnType;
    private javax.swing.JLabel labelCurrentColumnDataName;
    private javax.swing.JLabel labelCurrentColumnDataName1;
    private javax.swing.JLabel labelCurrentColumnDataName2;
    private javax.swing.JLabel labelCurrentColumnName;
    private javax.swing.JLabel labelNewColumnName;
    private javax.swing.JLabel labelSelectDatabaseName;
    private javax.swing.JLabel labelSelectTableName1;
    private javax.swing.JPanel panelTypeCurrentNewColumnName;
    private javax.swing.JScrollPane scrollPaneTypeCurrentNewColumnName;
    private javax.swing.JTextArea textAreaOutput;
    private javax.swing.JTextField textFieldNewColumnDataName;
    private javax.swing.JTextField textFieldNewColumnDataName1;
    private javax.swing.JTextField textFieldNewColumnDataName2;
    // End of variables declaration//GEN-END:variables
}
