/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qssproject;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author admin
 */
public class UserFriendlyModePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserFriendlyModePanel
     */
    public UserFriendlyModePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        scrollbarMenu = new javax.swing.JScrollBar();
        buttonCreateDatabase = new javax.swing.JButton();
        buttonCreateTable = new javax.swing.JButton();
        buttonDeleteTable = new javax.swing.JButton();
        buttonAlterTable = new javax.swing.JButton();
        buttonDeleteDatabase = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonSelectRecords = new javax.swing.JButton();
        buttonDeleteRecord = new javax.swing.JButton();
        buttonUpdateRecord = new javax.swing.JButton();
        buttonInsertRecord = new javax.swing.JButton();
        buttonBackToWelcomePage = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(495, 300));
        setPreferredSize(new java.awt.Dimension(495, 300));
        setSize(new java.awt.Dimension(495, 300));
        setLayout(null);

        panelMenu.setBackground(new java.awt.Color(204, 255, 204));
        panelMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelMenu.setToolTipText("");

        buttonCreateDatabase.setText("<html>Create<br> database</html>");
        buttonCreateDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateDatabaseActionPerformed(evt);
            }
        });

        buttonCreateTable.setText("<html>Create<br> table</html>");
        buttonCreateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateTableActionPerformed(evt);
            }
        });

        buttonDeleteTable.setText("<html>Delete<br> table</html>");
        buttonDeleteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteTableActionPerformed(evt);
            }
        });

        buttonAlterTable.setText("<html>Alter <br>table</html>");

        buttonDeleteDatabase.setText("<html>Delete<br> database</html>");
        buttonDeleteDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteDatabaseActionPerformed(evt);
            }
        });

        jButton1.setText("<html>Delete <br>database</html>");

        buttonSelectRecords.setText("<html>Select <br>record(s)</html>");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAlterTable)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonCreateTable)
                                .addComponent(buttonCreateDatabase)
                                .addComponent(buttonDeleteTable, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSelectRecords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollbarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buttonDeleteDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buttonCreateDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCreateTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeleteTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSelectRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollbarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(275, 275, 275)
                .addComponent(buttonAlterTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buttonDeleteDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        scrollbarMenu.add(buttonCreateDatabase);
        scrollbarMenu.add(buttonDeleteDatabase);
        scrollbarMenu.add(buttonCreateTable);
        scrollbarMenu.add(buttonDeleteTable);

        add(panelMenu);
        panelMenu.setBounds(0, 0, 130, 250);

        buttonDeleteRecord.setText("<html>Delete <br>record(s)</html>");
        add(buttonDeleteRecord);
        buttonDeleteRecord.setBounds(160, 240, 97, 40);

        buttonUpdateRecord.setText("<html>Update<br> record</html>");
        add(buttonUpdateRecord);
        buttonUpdateRecord.setBounds(160, 180, 100, 40);

        buttonInsertRecord.setText("<html>Insert<br> record(s)</html>");
        buttonInsertRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertRecordActionPerformed(evt);
            }
        });
        add(buttonInsertRecord);
        buttonInsertRecord.setBounds(160, 120, 100, 40);

        buttonBackToWelcomePage.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        buttonBackToWelcomePage.setForeground(new java.awt.Color(102, 0, 0));
        buttonBackToWelcomePage.setText("<Back");
        buttonBackToWelcomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackToWelcomePageActionPerformed(evt);
            }
        });
        add(buttonBackToWelcomePage);
        buttonBackToWelcomePage.setBounds(10, 260, 97, 29);

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeleteDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteDatabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteDatabaseActionPerformed

    private void buttonCreateDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateDatabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCreateDatabaseActionPerformed

    private void buttonCreateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCreateTableActionPerformed

    private void buttonDeleteTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteTableActionPerformed

    private void buttonInsertRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInsertRecordActionPerformed

    private void buttonBackToWelcomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackToWelcomePageActionPerformed
        this.setVisible(false);
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        WelcomePanel welcomePanel = new WelcomePanel();
        topFrame.add(welcomePanel);
        topFrame.pack();
        topFrame.setVisible(true);
    }//GEN-LAST:event_buttonBackToWelcomePageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterTable;
    private javax.swing.JButton buttonBackToWelcomePage;
    private javax.swing.JButton buttonCreateDatabase;
    private javax.swing.JButton buttonCreateTable;
    private javax.swing.JButton buttonDeleteDatabase;
    private javax.swing.JButton buttonDeleteRecord;
    private javax.swing.JButton buttonDeleteTable;
    private javax.swing.JButton buttonInsertRecord;
    private javax.swing.JButton buttonSelectRecords;
    private javax.swing.JButton buttonUpdateRecord;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JScrollBar scrollbarMenu;
    // End of variables declaration//GEN-END:variables
}
